### ISSUE TITLE
add dependencies for Linux to readme

### ISSUE THREAD

**Issue by georgfaust** [membraneframework/membrane_demo#106]
this could safe some time:

`sudo apt-get install libsrtp2-dev libnice-dev libavcodec-dev libavformat-dev libavutil-dev libopus-dev`

:+1:

**Comment by mat-hek** [comment]
Hi @georgfaust, which demo's readme do you mean?

**Comment by georgfaust** [comment]
sorry, its for the videoroom.
after installing thiese deps under ubuntu 20.04 everything works like a charm. great work.
