### ISSUE TITLE
QA - "Muted microphone" icon should have more visible color

### ISSUE THREAD

**Issue by WiktorSzwajka** [membraneframework/membrane_demo#112]
I think more people will have problem like mine. Shouldn't we change it to red (google chrome)?
<img width="1440" alt="Zrzut ekranu 2021-06-4 o 11 35 11" src="https://user-images.githubusercontent.com/42119979/120792670-2b485a80-c536-11eb-87ff-4e3e50f95903.png">

**Comment by mat-hek** [comment]
The best option IMO would be an icon with a visible border
