### ISSUE TITLE
Public deployments of demos

### ISSUE THREAD

**Issue by mat-hek** [membraneframework/membrane_demo#148]
Create and announce 'public' deployments of membrane demos, like videoroom demo and rtmp->HLS demo, so that everyone could test them. We need to impose some limits, not to crash servers in case of too big interest.

**Comment by mat-hek** [comment]
Regarding the directory structure in membrane_demo, I'd keep it as flat as possible, so that one doesn't have to check the directories to see what demos are available.

**Comment by mat-hek** [comment]
I think that using a different domain for demos (like membrane.stream) would only introduce confusion. I'd stick to membraneframework.org unless we decide to switch completely to another one

**Comment by piotrekzyla** [comment]
@bblaszkow06 
> I mean `demo.membraneframework.org` with a simple landing page listing all the demos and subdirectories (mapping to the ones in repo) with the actual demos, e.g. `demo.membraneframework.org/rtmp-to-hls`

This might introduce some problems in the way it is now deployed: depending. of course, on how this single-page app would be constructed. I would say `demo.membraneframework.org` could list all of the demos and links to `demo-videoroom.membraneframework.org`
