### ISSUE TITLE
Merge join and init methods in videoroom demo

### ISSUE THREAD

**Issue by andpodob** [membraneframework/membrane_demo#164]
I don't really understand an advantage of splitting [Room#init()](https://github.com/membraneframework/membrane_demo/blob/master/webrtc/videoroom/assets/src/room.ts#L82) and [Room#join()](https://github.com/membraneframework/membrane_demo/blob/master/webrtc/videoroom/assets/src/room.ts#L101) into separate functions. This design leads to a weird implementation in [index.ts](https://github.com/membraneframework/membrane_demo/blob/master/webrtc/videoroom/assets/src/index.ts#L4):
``` js
room.init().then(() => room.join());
```
which basically means that `room.join()` and `room.init()` are called synchronously one after another. I couldn't imagine any use case of calling the `room.init()` without calling the `room.join()`, at least in terms of our demo.

If there are no clear disadvantages of merging those functions into one (e.g. simply `join`) I would suggest doing so.

**Comment by Qizot** [comment]
Makes sense, PR is welcomed :)

**Comment by mat-hek** [comment]
cc @mickel8 @Rados13

**Comment by mickel8** [comment]
I think I did it in this way as I couldnt use async functions in `Room` constructor so I moved Room initialization to async `init` function. Maybe we could make join async and move init into it?

**Comment by varsill** [comment]
I have created pull request closing this issue: https://github.com/membraneframework/membrane_demo/pull/165
@mickel8 
I am not sure if making join async is the best option - I did it in such a manner that room.join() is now blocking. I cannot think about a situation in which something could be done meanwhile .join()'s execution.  On the other hand, making .join() asynchronous could lead to misleading usage of it as somebody could not be aware that he needs to await for it.

**Comment by Qizot** [comment]
> I think I did it in this way as I couldnt use async functions in `Room` constructor so I moved Room initialization to async `init` function. Maybe we could make join async and move init into it?

The pattern with entering async function is to create an async entry point, something like `main` and then run everything async inside of it (In our case running the main). Making the `Room` to be the entry point seems wrong.

>On the other hand, making .join() asynchronous could lead to misleading usage of it as somebody could not be aware that he needs to await for it.

Most of the stuff regarding the `Room` is asynchronous so there is no way to skip that, anyone who uses JS should be aware of its behaviour but I can agree on that it should be a single callback.
