### ISSUE TITLE
Use Genserver.cast() instead of GenServer.call() in webrtc/videoroom 

### ISSUE THREAD

**Issue by varsill** [membraneframework/membrane_demo#167]
Hello,
I was wondering if this is necessary to handle `:add_peer_channel event` with `handle_call()`
https://github.com/membraneframework/membrane_demo/blob/9cbcc6096edb31407af8971d141b6830be5affc5/webrtc/videoroom/lib/videoroom/room.ex#L46

Since we do not make use of the return value of this method, wouldn't it be better to make it asynchronous and handle with `handle_cast()`?

Then, of course, we would need to change it's invocation here:
https://github.com/membraneframework/membrane_demo/blob/9cbcc6096edb31407af8971d141b6830be5affc5/webrtc/videoroom/lib/videoroom/room.ex#L16

and use `GenServer.cast()` 

Another thing is - do we really need `add_peer_channel/3` wrapper? The only place where we invoke this method is here:
https://github.com/membraneframework/membrane_demo/blob/2bc1bf6eb4aa219ca86a1eb7bedceff27cecec14/webrtc/videoroom/lib/videoroom_web/peer_channel.ex#L17

We could simply use `GenServer.cast()` there.

**Comment by mat-hek** [comment]
This can actually be a regular `send`
