### ISSUE TITLE
Have anyone encounter this, could not comile dependency:p1_utils when I compile videoroom demo!

### ISSUE THREAD

**Issue by lifan0913** [membraneframework/membrane_demo#186]
===> Fetching pc v1.14.0
===> Version cached at /home/lifan/.cache/rebar3/hex/hexpm/packages/pc-1.14.0.tar is up to date, reusing it
escript: exception error: undefined function erlang:get_stacktrace/0
  in function  rebar3:main/1 (/tmp/cirrus-ci-build/src/rebar3.erl, line 72)
  in call from escript:run/2 (escript.erl, line 750)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
** (Mix) Could not compile dependency :p1_utils, "/home/lifan/.mix/rebar3 bare compile --paths /home/lifan/workspace/elixir/membrane_demo/webrtc/videoroom/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile p1_utils", update it with "mix deps.update p1_utils" or clean it with "mix deps.clean p1_utils"

**Comment by mat-hek** [comment]
Hi @lifan0913, what's your OS, Elixir and Erlang version?

**Comment by lifan0913** [comment]
OS is Debian 10 buster, elixir version is 1.13.0, erlang/OTP 24

**Comment by mat-hek** [comment]
No idea why this happens :( seems like an issue with https://github.com/processone/p1_utils/ . I'd try doing `mix deps.update` or try finding help there
