### ISSUE TITLE
Running locally doesn't show incomming video stream.

### ISSUE THREAD

**Issue by cristaloleg** [membraneframework/membrane_demo#201]
Hi, thanks for the membrane, it looks awesome.

Grain of salt, I have tried to run `membrane_videoroom` locally and encountered a problem: there is no incomming video input at all. I see what my webcam shows, in another tab/another browser/with and without anon mode I don't see any input.

I took recent version from master and have run Docker image, not sure this is related to my setup because Docker was built without errors or warnings. Can you help me with this, please?

(Not sure is this more relates to https://github.com/membraneframework/membrane_videoroom , this repo or even https://github.com/membraneframework/membrane_core feel free to move to another.)

**Comment by FelonEkonom** [comment]
Hi, have you published any ports or have you used the `--network="host"` option, when running the Docker image?

**Comment by cristaloleg** [comment]
I did literally the same as README suggests:
`docker run -p 4000:4000 --env-file .env membrane_videoroom_advanced`

Doing `--network="host'` (`docker run --network=host --env-file .env membrane_videoroom_advanced`) fails:
```

13:04:30.044 [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.

13:04:30.045 [warn]  Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.


13:04:30.131 [warn]  Integrated TURN certificate or private key path not specified.
Integrated TURN will not handle TLS connections.


13:04:30.132 [error] Failed to start Ranch listener VideoRoomWeb.Endpoint.HTTP in :ranch_tcp:listen([cacerts: :..., key: :..., cert: :..., port: 4000]) for reason :eaddrinuse (address already in use)


13:04:30.132 [info]  Application membrane_videoroom_demo exited: VideoRoom.Application.start(:normal, []) returned an error: shutdown: failed to start child: VideoRoomWeb.Endpoint
    ** (EXIT) shutdown: failed to start child: {:ranch_listener_sup, VideoRoomWeb.Endpoint.HTTP}
        ** (EXIT) an exception was raised:
            ** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a key that exists in the table

                (stdlib 3.15.2) :ets.lookup_element(:ranch_server, {:addr, VideoRoomWeb.Endpoint.HTTP}, 2)
                (ranch 1.8.0) /app/deps/ranch/src/ranch_server.erl:113: :ranch_server.get_addr/1
                (phoenix 1.6.9) lib/phoenix/endpoint/cowboy2_adapter.ex:119: Phoenix.Endpoint.Cowboy2Adapter.bound_address/2
                (phoenix 1.6.9) lib/phoenix/endpoint/cowboy2_adapter.ex:115: Phoenix.Endpoint.Cowboy2Adapter.info/3
                (phoenix 1.6.9) lib/phoenix/endpoint/cowboy2_adapter.ex:101: Phoenix.Endpoint.Cowboy2Adapter.start_link/3
                (stdlib 3.15.2) supervisor.erl:414: :supervisor.do_start_child_i/3
                (stdlib 3.15.2) supervisor.erl:400: :supervisor.do_start_child/2
                (stdlib 3.15.2) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
{"Kernel pid terminated",application_controller,"{application_start_failure,membrane_videoroom_demo,{{shutdown,{failed_to_start_child,'Elixir.VideoRoomWeb.Endpoint',{shutdown,{failed_to_start_child,{ranch_listener_sup,'Elixir.VideoRoomWeb.Endpoint.HTTP'},{'EXIT',{badarg,[{ets,lookup_element,[ranch_server,{addr,'Elixir.VideoRoomWeb.Endpoint.HTTP'},2],[{error_info,#{cause => badkey,module => erl_stdlib_errors}}]},{ranch_server,get_addr,1,[{file,\"/app/deps/ranch/src/ranch_server.erl\"},{line,113}]},{'Elixir.Phoenix.Endpoint.Cowboy2Adapter',bound_address,2,[{file,\"lib/phoenix/endpoint/cowboy2_adapter.ex\"},{line,119}]},{'Elixir.Phoenix.Endpoint.Cowboy2Adapter',info,3,[{file,\"lib/phoenix/endpoint/cowboy2_adapter.ex\"},{line,115}]},{'Elixir.Phoenix.Endpoint.Cowboy2Adapter',start_link,3,[{file,\"lib/phoenix/endpoint/cowboy2_adapter.ex\"},{line,101}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,414}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,400}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,384}]}]}}}}}},{'Elixir.VideoRoom.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,membrane_videoroom_demo,{{shutdown,{failed_to_start_child,'Elixir.VideoRoomWeb.Endpoint',{shutdown,{failed_to_start_child,{ra

Crash dump is being written to: erl_crash.dump...done
```

**Comment by FelonEkonom** [comment]
Command `docker run --network=host --env-file .env membrane_videoroom_advanced` is valid, version from `README.md` seems to be little outdated and we will fix it. Error, that you have put there, suggests, that port 4000 is already in use (`13:04:30.132 [error] Failed to start Ranch listener VideoRoomWeb.Endpoint.HTTP in :ranch_tcp:listen([cacerts: :..., key: :..., cert: :..., port: 4000]) for reason :eaddrinuse (address already in use)`). Are you sure you don't have another process listening on this port?

**Comment by cristaloleg** [comment]
Yeah, my bad, I had old version running in a background. `docker run --network=host --env-file .env membrane_videoroom_advanced` did actually start but the web panel isn't served anymore:

```
% curl -v localhost:4000  
*   Trying 127.0.0.1:4000...
* connect to 127.0.0.1 port 4000 failed: Connection refused
*   Trying ::1:4000...
* connect to ::1 port 4000 failed: Connection refused
* Failed to connect to localhost port 4000 after 7 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 4000 after 7 ms: Connection refused
```

is there another port to web panel? I don't see it in logs or README. Log btw:
```
% docker run --network=host --env-file .env membrane_videoroom_advanced                          

16:19:42.583 [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.

16:19:42.584 [warn]  Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.


16:19:42.656 [warn]  Integrated TURN certificate or private key path not specified.
Integrated TURN will not handle TLS connections.


16:19:42.657 [info]  Running VideoRoomWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)

16:19:42.657 [info]  Access VideoRoomWeb.Endpoint at http://localhost:4000
```

**Comment by FelonEkonom** [comment]
Hm, are you using Macbook? If so, there might be problems with options `--network=host`. You can also set range of ports, that will be published. Put these 2 addtional lines to your `.env` file 
```
INTEGRATED_TURN_PORT_RANGE=50000-50050
INTEGRATED_TURN_IP={IPv4 address of one of your network interfaces}
```
I suggest to set `INTEGRATED_TURN_IP` to `en0`, in my case it will be `INTEGRATED_TURN_IP=192.168.83.198`. You can get it from output of `ifconfig` command. 

Then, run `$ docker run -p 50000-50050:50000-50050/udp -p 4000:4000/tcp --env-file .env membrane_videoroom_advanced` in your command line.

**Comment by cristaloleg** [comment]
Yeah, Macbook/macOS. 

I confirm that specifying TURN ip/port solve the problem but still - locally 2 different tabs show only webcam input and nothing got streamed, log (should there be something else when someone else joins? is it possible to increase log level (if it makes sense)?
```
% podman run -p 50000-50050:50000-50050/udp -p 4000:4000/tcp --env-file .env membrane_videoroom_advanced

00:23:17.317 [error] `inotify-tools` is needed to run `file_system` for your system, check https://github.com/rvoicilas/inotify-tools/wiki for more information about how to install it. If it's already installed but not be found, appoint executable file with `config.exs` or `FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE` env.

00:23:17.318 [warn]  Could not start Phoenix live-reload because we cannot listen to the file system.
You don't need to worry! This is an optional feature used during development to
refresh your browser when you save files and it does not affect production.


00:23:17.352 [warn]  Integrated TURN certificate or private key path not specified.
Integrated TURN will not handle TLS connections.


00:23:17.353 [info]  Running VideoRoomWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)

00:23:17.353 [info]  Access VideoRoomWeb.Endpoint at http://localhost:4000

00:23:23.649 [info]  CONNECTED TO VideoRoomWeb.UserSocket in 72µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}

00:23:25.490 [info]  Spawning room process: #PID<0.2414.0>

00:23:25.490 [info]  Starting a new RTC Engine instance with id: 123

00:23:25.491 [info]  JOINED room:123 in 1ms
  Parameters: %{}

00:23:25.495 [info]  New peer: %Membrane.RTC.Engine.Peer{id: "e6ee6522-51d0-4833-b523-447bfda22e8c", metadata: %{"displayName" => "oleg"}}. Accepting.

00:23:34.321 [info]  CONNECTED TO VideoRoomWeb.UserSocket in 68µs
  Transport: :websocket
  Serializer: Phoenix.Socket.V2.JSONSerializer
  Parameters: %{"vsn" => "2.0.0"}

00:23:34.394 [info]  JOINED room:123 in 101µs
  Parameters: %{}

00:23:34.399 [info]  New peer: %Membrane.RTC.Engine.Peer{id: "69087547-be16-4083-b070-88f0091ff656", metadata: %{"displayName" => "anon"}}. Accepting.
```

I also have tried to connect from another laptop - same thing, so it's not just a problem of streaming locally.

Dumb idea: is it possible that browser doesn't send data? I have looked at network tab in console - no errors or logs.

(BTW, macbook with M1 processor, that's why I need to rebuild docker image, `docker run -p 4000:4000 --env-file .env membraneframework/demo_webrtc_videoroom_advanced:latest` will fail with `{"msg":"exec container process `/app/bin/membrane_videoroom_demo`: Exec format error","level":"error","time":"2022-06-28T00:21:09.000629571Z"}` but that's another problem and less relevant).

**Comment by FelonEkonom** [comment]
Problem, that you are describing, in fact, seems to look like browser is not sending media on server. 
Which browser do you use? If you use Safari or Firefox, try Google Chrome.
If it will not help, put `config :logger, level: :debug` to the `config/prod.exs` file (instead of `config :logger, level: :info`), rebuild docker image and run it again. You can also start wireshark with display filter `stun` while trying to connect to server and attach there output from it, data from it also might be helpful

**Comment by cristaloleg** [comment]
The recent one: Version 103.0.5060.53 (Official Build) (arm64)

I have tried to capture STUN traffic but no luck. Maybe I lost my Wireshark skills or maybe something isn't right with my mac.

**Comment by FelonEkonom** [comment]
I forgot, that to capture debug logs, you also have to comment out line no. 20 in `config/config.exs` (`[level_lower_than: :info],`). Your Chrome version is high enough, so it shouldn't be the reason of the problems. On which network interface do you run Wireshark?

**Comment by cristaloleg** [comment]
Oh, thanks for the log tip. TBH nothing much changed, nothing new was logged.

I'm capturing on `en0`, I see all the traffic but nothing for the STUN. Will verify later again.

**Comment by FelonEkonom** [comment]
Try capturing on Loopback, do you see any STUN messages there?

**Comment by cristaloleg** [comment]
Hm, this will sound stupid but Docker & Podman have different behaviour (I assume Podman is more restrictive and it fails somewhere earlier). Have build and run via Docker:
```
$ docker build  -t membrane_videoroom_advanced .
$ docker run -p 50000-50050:50000-50050/udp -p 4000:4000/tcp --env-file .env membrane_videoroom_advanced
```

And found in logs this:
`07:31:51.087 [debug] [:ice] ICE restart failed due to timeout`

full log https://gist.github.com/cristaloleg/3d0fcf209a357c5815c7f0de7e05bd95

**Comment by FelonEkonom** [comment]
Have you set `INTEGRATED_TURN_PORT_RANGE` env to `50000-50050` in `.env` file? Logs suggest, that variables, that should be equal to this env, are, in fact, equal to its default value, which is `50000-59999`. So, Videoroom opens a socket on a port, from this range and tries to exchange media with a browser through this socket, but this may not work, as long, as you publish only ports from the range 50000-50050. 

Another possibility is that the IP address in your private network has changed, so if this is not the problem with unset `INTEGRATED_TURN_PORT_RANGE` env, set `INTEGRATED_TURN_IP` again? In this [comment](https://github.com/membraneframework/membrane_demo/issues/201#issuecomment-1171009469) I have written about, what you have to put in `.env` file. If you have any doubts, you can take a look at it

**Comment by cristaloleg** [comment]
Yay, it works. Indeed config on host was default so the connection was outside the range. `INTEGRATED_TURN_IP` also.

Thanks for helping, works perfectly! <3
