### ISSUE TITLE
React Example

### ISSUE THREAD

**Issue by the-wc** [membraneframework/membrane_demo#211]
This is just a recommendation, but would someone be able to provide a video room example using React in this repository? 

Demonstrating how to extend the `Room` class in the  [video conference tutorial](https://membrane.stream/learn/videoroom/2) would be sufficient, as managing the state of the `WebRTCEngine` is difficult.

**Comment by mickel8** [comment]
Please check out our new Media Server and its examples https://github.com/jellyfish-dev
