### ISSUE TITLE
compiler error on 

### ISSUE THREAD

**Issue by cdesch** [membraneframework/membrane_demo#23]
Ran into this issue on MacOS 10.14.6 (18G5033). I'm going to try it on the membrane docker image instead. 

```
cjs-MBP13-2017:rtp_to_hls cj$ mix run --no-halt
==> crc
 LD     crc_nif.so
ld: library not found for -lerl_interface
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/cj/elixir_projects/membrane_demo/rtp_to_hls/deps/crc/priv/crc_nif.so] Error 1
could not compile dependency :crc, "mix compile" failed. You can recompile this dependency with "mix deps.compile crc", update it with "mix deps.update crc" or clean it with "mix deps.clean crc"
==> membrane_demo_rtp_to_hls
** (Mix) Could not compile with "make" (exit status: 2).
You need to have gcc and make installed. Try running the
commands "gcc --version" and / or "make --version". If these programs
are not installed, you will be prompted to install them.
```

**Comment by mickel8** [comment]
Hi @cdesch,
what is your Erlang version? 
Erlang 23.0 deprecated `erl_interface.h` and we haven't updated our dependencies yet.
Running example on Erlang 22.3 should work properly

**Comment by mickel8** [comment]
Versions [0.5.1](https://github.com/membraneframework/membrane_aac_plugin/releases/tag/v0.5.1) of `membrane_aac_plugin` and [0.3.1](https://github.com/membraneframework/membrane-element-flac-parser/releases/tag/v0.3.1) of `membrane_aac_plugin` have been released so I am closing this issue. Feel free to reopen if any further problems occur.
