### ISSUE TITLE
Libav is disabled because it unmaintained

### ISSUE THREAD

**Issue by mechamogeo** [membraneframework/membrane_demo#230]
# Cannot run the exemples

In some demonstrations, I really can't run the code because the `membrane_h264_ffmpeg_plugin` requires the `libav` as `libavcodec` and `libavutil`, but the dependencies cannot get installed anymore, because the `libav` is no longer maintained, also the brew has disabled the installation, and trying compile they on my Mac doesn't work.

Running the installation brew at my terminal only returns this message:
```shell
Error: libav has been disabled because it is not maintained upstream!
```

And inside brew libav homepage is the message:
```diff
- This formula has been disabled since 2022-07-31 because it unmaintained
```

Here some footage of my terminal recorded with asciinema
[![asciicast](https://asciinema.org/a/rQ3bQh3ddiwL6Hs1APatQrJUY.svg)](https://asciinema.org/a/rQ3bQh3ddiwL6Hs1APatQrJUY)

**Comment by mechamogeo** [comment]
I opened an issue at plugin with the error membraneframework/membrane_h264_ffmpeg_plugin#77

**Comment by bblaszkow06** [comment]
Just as mentioned here https://github.com/membraneframework/membrane_h264_ffmpeg_plugin/issues/77#issuecomment-1669159896, the problem comes from using `libav` instead of FFmpeg, which is maintained and available via `brew`.
