### ISSUE TITLE
what are dependencies in Ubuntu in demo project webrtc_to_hls ?

### ISSUE THREAD

**Issue by chanphiromsok** [membraneframework/membrane_demo#233]
in mac os, you have instructions for the installation of mac Os dependencies how about Linux (Unbuntu ,Debain)?
https://github.com/membraneframework/membrane_demo/tree/master/webrtc_to_hls

**Comment by mickel8** [comment]
Hi @chanphiromsok,

I believe that those packages are correct for Ubuntu:

```
sudo apt-get install libsrtp2-dev libavcodec-dev libavformat-dev libavutil-dev libopus-dev libfdk-aac-dev
```
