### ISSUE TITLE
DataChannels Demo

### ISSUE THREAD

**Issue by ris-home** [membraneframework/membrane_demo#240]
It would be great if there is a DataChannel only peer demo. I have written a DataChannel wrapper in JS and in Rust (webrtc-rs) but am unfortunately not experienced enough in Elixir. It would be great as there are some use cases which only involve DataChannels (like P2P file sharing, WebTorrents, etc.) than any of the video/multimedia elements.

Please consider adding a demo for pure DataChannels as well, if it is within the scope of this project. Thank you.

Moreover, I have tried the other demos and they have been amazing and I have not seen such a simple to deploy application -- it was simpler than Jitsi and more lightweight too!

**Comment by mat-hek** [comment]
Hi, thanks for your kind words. Unfortunately, we don't support data channels. The support is planned for our new, pure Elixir WebRTC implementation https://github.com/elixir-webrtc, but it's not there yet.
