### ISSUE TITLE
Unable to compile demo projects

### ISSUE THREAD

**Issue by IkechukwuAKalu** [membraneframework/membrane_demo#32]
Hello,

Please I am been unable to compile the demo projects. I have tried the `sample_pipleine`, `sample_element` and `rtp` projects but none has run successfully. 

For the `sample_element`, I have installed `portaudio19` and `clang-format` but it still doesn't compile. It shows the following error message: 

```
fatal error: libavutil/channel_layout.h: No such file or directory
#include <libavutil/channel_layout.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Any help would be really appreciated. Thanks

**Comment by mickel8** [comment]
Hi,
it seems that you are missing  `libavutil` library. You can probably get it by installing ffmpeg e.g. (for Ubuntu)
```bash
sudo apt install ffmpeg
```

**Comment by IkechukwuAKalu** [comment]
Hi @mickel8 , thanks for your response.

I have installed `ffmpeg` and when I run `sudo apt search libavutil`, I get the following:
```
Sorting... Done
Full Text Search... Done
libavutil-dev/xenial-updates,xenial-security 7:2.8.17-0ubuntu0.1 amd64
  FFmpeg library with functions for simplifying programming - development files

libavutil-ffmpeg54/xenial-updates,xenial-security,now 7:2.8.17-0ubuntu0.1 amd64 [installed,automatic]
  FFmpeg library with functions for simplifying programming - runtime files
```

I guess that means that `ffmpeg` made the `libavutil` library available. But when I run the project using `mix run --no-halt run.exs`, I still get the missing file error

```
membrane_demo/simple_element/deps/membrane_ffmpeg_swresample_plugin/c_src/membrane_ffmpeg_swresample_plugin/_generated/nif/../../converter_lib.h:1:38: fatal error: libavutil/channel_layout.h: No such file or directory
```

**Comment by bblaszkow06** [comment]
Hey @IkechukwuAKalu! You need to install the `-dev` package as well (or even packages if libavutil is not the only one missing) 

Anyway, I guess the READMEs for the mentioned demos require updates @mickel8

**Comment by IkechukwuAKalu** [comment]
Hi @bblaszkow06 , I have added the `-dev` package as well as some additional packages and the `simple_element` project is working now. 

In case someone else experiences issues during setup, these are the packages I had to install for Ubuntu 16.04 using `apt`
```
clang-format, portaudio19-dev, ffmpeg, libavutil-dev, libswresample-dev, libmad0 libmad0-dev
```

Thanks so much @mickel8 and @bblaszkow06 for your help!
