### ISSUE TITLE
[Videoroom] Stacktrace from server is displayed in browser

### ISSUE THREAD

**Issue by mickel8** [membraneframework/membrane_demo#59]
It seems we send error/stacktrace from server to client and it is displayed in web browser. 

![image](https://user-images.githubusercontent.com/24651552/114033783-d82b9180-987d-11eb-9cd5-795747012c8c.png)

**Comment by Qizot** [comment]
I did it on purpose so anyone could report the error without having to look it up in the server logs. At the end we don't want that but I think that it quite useful for now.

**Comment by mickel8** [comment]
Ahh I see. I will leave this issue to remeber to remove it at the end
