### ISSUE TITLE
rtp_to_hls demo handle_notification callback incorrect arity

### ISSUE THREAD

**Issue by DaniruKun** [membraneframework/membrane_demo#65]
In new API as described here for `Pipeline` https://hexdocs.pm/membrane_core/Membrane.Pipeline.html#c:handle_notification/4

the `handle_notification` callback now also expects a 4th context argument. Would be great to update the example with this in mind, as well as provide an example of such context.

**Comment by mat-hek** [comment]
That's because that demo uses core v0.5.2, while the context was added in v0.6.0 if I recall correctly. The context is documented [here](https://hexdocs.pm/membrane_core/Membrane.Pipeline.CallbackContext.Notification.html#t:t/0)

**Comment by mickel8** [comment]
@DaniruKun a new version of rtp_to_hls demo has been merged. You can take a look at it here https://github.com/membraneframework/membrane_demo/tree/master/rtp_to_hls

**Comment by DaniruKun** [comment]
Hi, thanks you! Will give it a go again.
