### ISSUE TITLE
Videoroom test

### ISSUE THREAD

**Issue by Qizot** [membraneframework/membrane_demo#67]
- leave it for 3h and see if it works
- disable wifi during call
- kill one participant (not gracefully) and see how it is handled
- connect from all major browsers (chrome, ff, safari)
- connect from mobile device
- connect with no permissions to camera/mic

**Comment by Qizot** [comment]
1. Turning off wi-fi:

Participant with  turned off wi-fi gets an immediate error message with all videos being freezed.

Other participants see one frozen video tag and it gets deleted after 30 seconds 
(I guess it is due to phoenix socket reconnection timeout beint set to 30 seconds).

Room works as expected, nothing crashes.

2. Connect from all major browsers:

- Google Chrome - fully working on both remote and local server
- Safari - fully working  on both remote and local server
- Firefox - partially working locally (can't start screensharing due to DTLS certificate errors), 
  doesn't work remotly due to DTLS retransmission not being supported in `ex_dtls`. Retransmission errors
  may occur in other browsers too but currently only happens on firefox. If such error happens the whole room
  crashes.

3. Connect from mobile device:

Tested on android phone.

Google Chrome:
 - receiving/sending audio and video works
 - video quality displayed on phone is fine but received by other peers is pretty bad
 - screensharing button on phone does nothing

Firefox:
 - mobile version not working just like with desktop

There is a layout problem on mobile when keeping phone vertically. The video is verticall as well and breaks the layout for both mobile and desktop.

4. Connect without camera/microphone permission:

An instant error message is shown -> "Failed to setup video room, make sure to grant camera and microphone permissions".
No video tags of other participants are shown.

It does not influence already running room.

5. Leave it running for 3 hours:

I've tested a videoroom for 1,5h and it happened that it had memory and cnode leaks. It has been fixed in several packages `membrane_ice_plugin` and `membrane_dtls_plugin`. The room kept working though without any crash.

Tested with 2 peers.

**Comment by WiktorSzwajka** [comment]
I have tested those cases and added to regression cycle.
