### ISSUE TITLE
QA - Front camera should be set as default 

### ISSUE THREAD

**Issue by WiktorSzwajka** [membraneframework/membrane_demo#93]
I think so, thats it's much easier for user to use front camera.  If we don't want to make it default we should add opportunity to swap between camera (back or front) on Smartphones

**Comment by bblaszkow06** [comment]
Choosing front camera as default simply comes down to calling `getUserMedia` with proper constraint:
```ts
navigator.mediaDevices.getUserMedia({audio: true, video: { facingMode: "user" }});
```
